# Use the official gcc image, based on debian.
# It can use version tags as well, like gcc:5.2.
# See https://hub.docker.com/_/gcc/ for more info.
image: gcc

build:
  stage: build
  before_script:
    - apt-get update && apt-get -y install cmake catch libglib2.0-dev libmongo-client-dev
  script:
    - ./ci/cpplint.sh
    - mkdir ./build
    - cd ./build
    - cmake ../
    - make -j4
    - ctest -V

coverage:
  image: debian:11-slim
  stage: test
  before_script:
    - apt-get update && apt-get -y upgrade
    - apt-get install -y catch cmake g++-10 lcov libglib2.0-dev libmongo-client-dev pkg-config
  script:
    # build
    - export CXX=g++-10
    - export CC=gcc-10
    - mkdir build-coverage
    - cd build-coverage
    - cmake -DCODE_COVERAGE=ON ../
    - make -j4
    # tests
    - ctest -V
    # collect code coverage data
    - lcov -c --directory . --output-file main_coverage.info
    - lcov --remove main_coverage.info '/usr/include/*' '*tests/*' '*third-party/*' -o main_coverage_filtered.info
    - genhtml main_coverage_filtered.info --output-directory ../public
  coverage: /^[\t ]*lines\.*:\s*\d+.\d+\%/
  artifacts:
    name: ${CI_JOB_NAME}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHA}
    expire_in: 2 days
    paths:
      - public

pages:
  image: debian:11-slim
  stage: deploy
  needs: ["coverage"]
  dependencies:
  - coverage
  script:
    - ls -l
  artifacts:
    paths:
      - public
