language: cpp
compiler:
  - gcc
sudo: false
dist: bionic
addons:
  apt:
    packages:
    - cmake
    - catch
    - libglib2.0-dev
    - libmongo-client-dev
script:
  - ./ci/cpplint.sh
  - mkdir ./build
  - cd ./build
  - cmake ../
  - make -j4
  - ctest -V
notifications:
  email: false
