name: GCC

on: push

jobs:
  gcc:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - version: 9
            os: ubuntu-22.04
          - version: 10
            os: ubuntu-24.04
          - version: 11
            os: ubuntu-24.04
          - version: 12
            os: ubuntu-24.04
          - version: 13
            os: ubuntu-24.04
          - version: 14
            os: ubuntu-24.04
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v4
      - name: Install Debian packages
        run: |
          sudo apt-get update
          sudo apt-get install -y catch cmake g++-${{ matrix.version }} git libglib2.0-dev libmongo-client-dev pkg-config
      - name: Build with GNU GCC ${{ matrix.version }}
        run: |
          export CXX=g++-${{ matrix.version }}
          export CC=gcc-${{ matrix.version }}
          cd $GITHUB_WORKSPACE && pwd
          mkdir build
          cd build
          cmake ../
          cmake --build . -j2
      - name: Tests
        run: |
          cd "$GITHUB_WORKSPACE"/build
          ctest -V
      - name: Build statically linked with GNU GCC ${{ matrix.version }}
        run: |
          export CXX=g++-${{ matrix.version }}
          export CC=gcc-${{ matrix.version }}
          cd $GITHUB_WORKSPACE
          mkdir build-static
          cd build-static
          cmake -DENABLE_LTO=ON -DENABLE_STATIC_LINKING=ON ../
          cmake --build . -j2
        # Only run static build on one version in the matrix.
        if: matrix.version == 12
