name: MSVC

on: push

jobs:
  windows_msvc:
    strategy:
      fail-fast: false
      matrix:
        version: [2022, 2025]
    runs-on: windows-${{ matrix.version }}
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - name: Checkout
        uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Build with Visual Studio 2022 on Windows Server ${{ matrix.version }}
        run: |
          cd "%GITHUB_WORKSPACE%"
          md build
          cd build
          cmake ..
          cmake --build .
        shell: cmd
      - name: Tests
        run: |
          cd "%GITHUB_WORKSPACE%\build"
          ctest -C Debug -V
        shell: cmd
