name: MSYS2

on: push

jobs:
  msys2_mingw64:
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE.
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: >-
            git
            mingw-w64-x86_64-catch
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-ninja
            mingw-w64-x86_64-pkg-config
      - name: Build
        run: |
          export MSYSTEM=MINGW64
          export CXX=g++
          export CC=gcc
          cd "$GITHUB_WORKSPACE"
          mkdir build
          cd build
          cmake ../
          cmake --build . -j4
      - name: Tests
        run: |
          export MSYSTEM=MINGW64
          cd "$GITHUB_WORKSPACE"/build
          ctest -V
      - name: Build statically linked
        run: |
          export MSYSTEM=MINGW64
          export CXX=g++
          export CC=gcc
          cd "$GITHUB_WORKSPACE"
          mkdir build-static
          cd build-static
          cmake -DENABLE_LTO=ON -DENABLE_STATIC_LINKING=ON ../
          cmake --build . -j2
      - name: Collect build artifacts
        run: |
          export MSYSTEM=MINGW64
          cd "$GITHUB_WORKSPACE"
          mkdir artifacts
          # engine
          mkdir -p "$GITHUB_WORKSPACE"/artifacts/simple-chess-engine
          cp build-static/apps/engine/*.exe artifacts/simple-chess-engine/
          cp apps/engine/*.md artifacts/simple-chess-engine/
          # pgn-reader
          mkdir -p "$GITHUB_WORKSPACE"/artifacts/pgn-reader
          cp build-static/apps/pgn-reader/*.exe artifacts/pgn-reader/
          cp apps/pgn-reader/*.md artifacts/pgn-reader/
          cp -R apps/pgn-reader/examples artifacts/pgn-reader/examples
          # simple-chess-cli
          mkdir -p "$GITHUB_WORKSPACE"/artifacts/simple-chess-cli
          cp build-static/apps/simple-chess-cli/*.exe artifacts/simple-chess-cli/
          cp apps/simple-chess-cli/*.md artifacts/simple-chess-cli/
          # license + readme + changelog + third-party notices
          cp LICENSE artifacts/
          cp apps/readme_package.md artifacts/readme.md
          cp changelog.md artifacts/
          cp apps/third-party.md artifacts/
          # determine version
          VERSION=$(git describe --always)
          echo Version is $VERSION.
          mv artifacts simple-chess-$VERSION
          "C:\Program Files\7-Zip\7z.exe" a -r simple-chess-$VERSION-win64.zip simple-chess-$VERSION
      - name: Upload zipped updater
        uses: actions/upload-artifact@v4
        with:
          name: simple-chess-win64
          if-no-files-found: error
          path: simple-chess-*.zip
